// <auto-generated />
namespace YellowPages.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAndUpdatedCities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAndUpdatedCities));
        
        string IMigrationMetadata.Id
        {
            get { return "201612251727262_AddAndUpdatedCities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
